title: Pei-Mei Lee
logo: /assets/img/Lee_Pei-Mei_HIL2622.jpeg
descripttion: Trilingual Data Analyst
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
