title: Pei-Mei Lee
logo: /assets/img/Lee_Pei-Mei_HIL2622.jpg
#description:
#lee.peimei@gmail.com <br> +49 160 899 5910 <br> Stuttgart, Germany <br> linkedin.com/in/peimeilee
#show_downloads: true
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
